[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "CLM5_cases"
version = "0.1.0"
dependencies = [
	"requests",
   	'importlib-metadata; python_version>="3.10"',
]

[tool.setuptools]
packages = ["CLM5_cases",]
package-dir = {"" = "src"}
